<?php
define('CHARSHANBE_API_NO_ROUTER', true);
require_once __DIR__ . '/api.php';
$pdo = db();
function csvRows(array $file): array {
    if (empty($file['tmp_name']) || !is_uploaded_file($file['tmp_name'])) return [];
    $rows = []; $fh = fopen($file['tmp_name'], 'r'); if (!$fh) return [];
    $header = null;
    while (($r = fgetcsv($fh, 0, ',')) !== false) {
        if ($r === [null] || count(array_filter($r, fn($v)=>trim((string)$v)!=='')) === 0) continue;
        $r = array_map(fn($v)=>trim((string)$v), $r);
        if ($header === null) { $header = $r; if (isset($header[0])) $header[0] = preg_replace('/^\xEF\xBB\xBF/', '', $header[0]); continue; }
        $rows[] = array_combine($header, array_pad($r, count($header), '')) ?: [];
    }
    fclose($fh); return $rows;
}
function val(array $r, array $keys, $default='') { foreach ($keys as $k) if (array_key_exists($k,$r) && $r[$k] !== '') return $r[$k]; return $default; }
$msgs = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $pdo->beginTransaction();
    try {
        if (!empty($_FILES['people']['tmp_name'])) {
            $st=$pdo->prepare('INSERT INTO students (name, absences, late_count, score, status, image, manual_score, bio, phones, parent_phone, dob, school, medical) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE image=VALUES(image), bio=VALUES(bio), phones=VALUES(phones), parent_phone=VALUES(parent_phone), dob=VALUES(dob), school=VALUES(school), medical=VALUES(medical), manual_score=VALUES(manual_score)');
            $n=0; foreach(csvRows($_FILES['people']) as $r){ $name=val($r,['نام','name']); if($name==='') continue; $phones=[]; foreach([['متربی','تلفن_متربی'],['والدین','تلفن_والدین']] as $p) if(val($r,[$p[1]])!=='') $phones[]=['label'=>$p[0],'number'=>val($r,[$p[1]])]; $st->execute([$name,(int)val($r,['غیبت'],0),(int)val($r,['تاخیر'],0),(float)val($r,['امتیاز'],0),val($r,['وضعیت'],'ثبت نام'),val($r,['عکس'],''),(float)val($r,['امتیاز_دستی'],0),val($r,['بیوگرافی'],''),json_encode($phones,JSON_UNESCAPED_UNICODE),val($r,['تلفن_والدین'],''),val($r,['تولد'],''),val($r,['مدرسه'],''),val($r,['پزشکی'],'')]); $n++; } $msgs[]="افراد: $n ردیف";
        }
        if (!empty($_FILES['notes']['tmp_name'])) { $st=$pdo->prepare('INSERT INTO notes (note_date,note_text) VALUES (?,?)'); $n=0; foreach(csvRows($_FILES['notes']) as $r){ $t=val($r,['یادداشت','text']); if($t==='') continue; $st->execute([normalizeDateStr(val($r,['تاریخ','date'])), $t]); $n++; } $msgs[]="یادداشت‌ها: $n ردیف"; }
        if (!empty($_FILES['plans']['tmp_name'])) { $st=$pdo->prepare('INSERT INTO plans (id, plan_date, title, priority, modules, sin, status) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE plan_date=VALUES(plan_date), title=VALUES(title), priority=VALUES(priority), modules=VALUES(modules), sin=VALUES(sin), status=VALUES(status)'); $n=0; foreach(csvRows($_FILES['plans']) as $r){ $id=val($r,['ID','id'],(string)round(microtime(true)*1000).$n); $st->execute([$id, normalizeDateStr(val($r,['تاریخ','date'])), val($r,['عنوان','title']), val($r,['اولویت','priority'],'low'), val($r,['ماژول‌ها','modules'],'[]'), val($r,['سین','sin'],''), val($r,['وضعیت','status'],'Active')]); $n++; } $msgs[]="طرح درس: $n ردیف"; }
        if (!empty($_FILES['archive']['tmp_name'])) { $st=$pdo->prepare('INSERT INTO archive_logs (log_date,log_type,title,details_json) VALUES (?,?,?,?)'); $n=0; foreach(csvRows($_FILES['archive']) as $r){ $st->execute([normalizeDateStr(val($r,['تاریخ','date'])), val($r,['نوع','type'],'other'), val($r,['عنوان','title']), val($r,['جزئیات_JSON','details'],'')]); $n++; } $msgs[]="آرشیو: $n ردیف"; }
        if (!empty($_FILES['mi_logs']['tmp_name'])) { $n=0; foreach(csvRows($_FILES['mi_logs']) as $r){ $name=val($r,['نام_متربی','name']); $s=getStudentByName($pdo,$name); if(!$s) continue; $pdo->prepare('INSERT INTO mi_logs (log_date,student_id,mi_type,behavior,score) VALUES (?,?,?,?,?)')->execute([date('Y-m-d H:i:s', strtotime(val($r,['تاریخ','date'],'now'))), $s['id'], val($r,['نوع_هوش','type']), val($r,['رفتار_مشاهده_شده','behavior']), (int)val($r,['امتیاز','score'],0)]); $n++; } $msgs[]="لاگ هوش: $n ردیف"; }
        if (!empty($_FILES['attendance']['tmp_name'])) { $n=0; foreach(csvRows($_FILES['attendance']) as $r){ $name=val($r,['نام','name']); if($name==='') continue; addStudent($pdo,$name); $student=getStudentByName($pdo,$name); foreach($r as $date=>$statusText){ if(in_array($date,['نام','name'],true)||trim($statusText)==='') continue; $date=normalizeDateStr($date); $pdo->prepare('INSERT INTO attendance_sessions (session_date) VALUES (?) ON DUPLICATE KEY UPDATE session_date=VALUES(session_date)')->execute([$date]); $sid=(int)$pdo->query('SELECT id FROM attendance_sessions WHERE session_date='.$pdo->quote($date))->fetchColumn(); $st='Present'; $mins=0; if(str_contains($statusText,'غیبت')) $st='Absent'; elseif(str_contains($statusText,'تاخیر')) { $st='Late'; preg_match('/(\d+)/', toEnglishDigits($statusText), $m); $mins=(int)($m[1]??0); } elseif(str_contains($statusText,'موجه')) $st='Excused'; $pdo->prepare('INSERT INTO attendance_records (session_id,student_id,status,late_minutes,status_text) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status), late_minutes=VALUES(late_minutes), status_text=VALUES(status_text)')->execute([$sid,$student['id'],$st,$mins,$statusText]); $n++; }} $msgs[]="حضور و غیاب: $n سلول"; }
        updateCalculations($pdo); $pdo->commit();
    } catch(Throwable $e) { $pdo->rollBack(); $msgs[]='خطا: '.$e->getMessage(); }
}
?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ورود CSV</title><style>body{font-family:Tahoma;background:#efe7d2;color:#172033;padding:24px}.box{max-width:760px;margin:auto;background:#fffaf0;border:1px solid #c9aa6b;border-radius:24px;padding:24px;box-shadow:0 20px 60px #0002}label{font-weight:bold;display:block;margin-top:14px}input{width:100%;padding:12px;border:1px solid #c9aa6b;border-radius:12px;background:#fff}button,a.btn{display:inline-block;margin-top:20px;background:#172033;color:#f8e7b0;border:0;padding:14px 22px;border-radius:14px;text-decoration:none;font-weight:bold}.msg{background:#e7f7df;border:1px solid #80b66b;padding:12px;border-radius:12px;margin:10px 0}</style></head><body><div class="box"><h1>ورود یک‌باره اطلاعات Google Sheet با CSV</h1><p>از هر شیت خروجی CSV بگیر و اینجا انتخاب کن. لازم نیست همه فایل‌ها را یک‌جا بدهی؛ هرکدام را داشتی انتخاب کن.</p><?php foreach($msgs as $m) echo '<div class="msg">'.htmlspecialchars($m,ENT_QUOTES,'UTF-8').'</div>'; ?><form method="post" enctype="multipart/form-data"><label>افراد</label><input type="file" name="people" accept=".csv"><label>حضور و غیاب</label><input type="file" name="attendance" accept=".csv"><label>یادداشت جلسات</label><input type="file" name="notes" accept=".csv"><label>طرح درس کامل</label><input type="file" name="plans" accept=".csv"><label>لاگ هوش</label><input type="file" name="mi_logs" accept=".csv"><label>سوابق فعالیت / آرشیو</label><input type="file" name="archive" accept=".csv"><button>شروع ورود اطلاعات</button> <a class="btn" href="index.php">بازگشت به سیستم</a></form></div></body></html>
